/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplikasidonasi;

/**
 *
 * @author Alghiiii
 */
public class formMenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form formMenuUtama
     */
    public formMenuUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuDonasi = new javax.swing.JMenu();
        miKelolaDonasi = new javax.swing.JMenuItem();
        miRiwayatDonasi = new javax.swing.JMenuItem();
        menuReport = new javax.swing.JMenu();
        miLaporanDonasi = new javax.swing.JMenuItem();
        menuAkun = new javax.swing.JMenu();
        miUbahPassword = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuDonasi.setText("Donasi");

        miKelolaDonasi.setText("Kelola Donasi");
        menuDonasi.add(miKelolaDonasi);

        miRiwayatDonasi.setText("Riwayat Donasi");
        menuDonasi.add(miRiwayatDonasi);

        jMenuBar1.add(menuDonasi);

        menuReport.setText("Report");

        miLaporanDonasi.setText("Laporan Donasi");
        menuReport.add(miLaporanDonasi);

        jMenuBar1.add(menuReport);

        menuAkun.setText("Akun");

        miUbahPassword.setText("Ubah Password");
        menuAkun.add(miUbahPassword);

        jMenuBar1.add(menuAkun);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formMenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuAkun;
    private javax.swing.JMenu menuDonasi;
    private javax.swing.JMenu menuReport;
    private javax.swing.JMenuItem miKelolaDonasi;
    private javax.swing.JMenuItem miLaporanDonasi;
    private javax.swing.JMenuItem miRiwayatDonasi;
    private javax.swing.JMenuItem miUbahPassword;
    // End of variables declaration//GEN-END:variables
}
